spring.application.name=springboot-mycqrs-commnd
server.port=8081

#cloud rabbit mq config
spring.rabbitmq.host=cougar.rmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=zxlgzpff
spring.rabbitmq.password=E95CgT89YVuoh4QR8ZKTg-uUH2fbrbQe
spring.rabbitmq.virtual-host=zxlgzpff

#config rabbit topic exchange
myapp.rabbitmq.exchange=myCqrsTopic


#cloud monggo config
spring.data.mongodb.uri=mongodb://ajbinarto:training123@ac-ymb0ejd-shard-00-00.v31avkv.mongodb.net:27017,ac-ymb0ejd-shard-00-01.v31avkv.mongodb.net:27017,ac-ymb0ejd-shard-00-02.v31avkv.mongodb.net:27017/mycqrs-jonet?ssl=true&replicaSet=atlas-sum0t4-shard-0&authSource=admin&retryWrites=true&w=majority&appName=Cluster-jonet
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver=INFO
